spring.application.name=Splitwise

spring.datasource.url=jdbc:postgresql://localhost:5432/splitwise
spring.datasource.username=psql
spring.datasource.password=psql123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

